language: node_js

node_js:
  - "9.2.1"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  fqdn: 'hooplife.site'
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master